import type { CustomerAccount, Loan } from "./type";


export const MOCK_LOANS: Loan[] = [
  {
    loan_id: 1001,
    customer_id: 101,
    customer_name: 'John Doe',
    customer_email: 'john.doe@example.com',
    loan_type: 'Personal Loan',
    amount: '50,000',
    duration_months: 24,
    interest_rate: '8.5%',
    purpose: 'Home Renovation',
    status: 'pending',
    employment_status: 'Employed',
    monthly_income: '5,500',
    id_doc_url: '/documents/john_id.pdf',
    bank_stmt_url: '/documents/john_bank.pdf',
    created_at: '2024-03-15T10:30:00Z',
  },
  {
    loan_id: 1002,
    customer_id: 102,
    customer_name: 'Jane Smith',
    customer_email: 'jane.smith@example.com',
    loan_type: 'Business Loan',
    amount: '150,000',
    duration_months: 36,
    interest_rate: '7.2%',
    purpose: 'Business Expansion',
    status: 'approved',
    employment_status: 'Self-Employed',
    monthly_income: '8,200',
    id_doc_url: '/documents/jane_id.pdf',
    bank_stmt_url: '/documents/jane_bank.pdf',
    created_at: '2024-02-20T14:15:00Z',
  },
  {
    loan_id: 1003,
    customer_id: 103,
    customer_name: 'Michael Johnson',
    customer_email: 'michael.j@example.com',
    loan_type: 'Auto Loan',
    amount: '35,000',
    duration_months: 60,
    interest_rate: '6.8%',
    purpose: 'Vehicle Purchase',
    status: 'disbursed',
    employment_status: 'Employed',
    monthly_income: '6,800',
    id_doc_url: '/documents/michael_id.pdf',
    bank_stmt_url: '/documents/michael_bank.pdf',
    created_at: '2024-01-10T09:45:00Z',
  },
  {
    loan_id: 1004,
    customer_id: 104,
    customer_name: 'Sarah Williams',
    customer_email: 'sarah.w@example.com',
    loan_type: 'Home Loan',
    amount: '500,000',
    duration_months: 240,
    interest_rate: '5.5%',
    purpose: 'Home Purchase',
    status: 'active',
    employment_status: 'Employed',
    monthly_income: '12,000',
    id_doc_url: '/documents/sarah_id.pdf',
    bank_stmt_url: '/documents/sarah_bank.pdf',
    created_at: '2023-06-01T11:20:00Z',
  },
  {
    loan_id: 1005,
    customer_id: 105,
    customer_name: 'Robert Brown',
    customer_email: 'robert.brown@example.com',
    loan_type: 'Personal Loan',
    amount: '25,000',
    duration_months: 12,
    interest_rate: '9.2%',
    purpose: 'Debt Consolidation',
    status: 'rejected',
    employment_status: 'Unemployed',
    monthly_income: '2,000',
    id_doc_url: '/documents/robert_id.pdf',
    bank_stmt_url: '/documents/robert_bank.pdf',
    created_at: '2024-03-18T13:30:00Z',
  },
  {
    loan_id: 1006,
    customer_id: 106,
    customer_name: 'Emily Davis',
    customer_email: 'emily.davis@example.com',
    loan_type: 'Education Loan',
    amount: '80,000',
    duration_months: 120,
    interest_rate: '6.0%',
    purpose: 'Higher Education',
    status: 'active',
    employment_status: 'Student',
    monthly_income: '1,500',
    id_doc_url: '/documents/emily_id.pdf',
    bank_stmt_url: '/documents/emily_bank.pdf',
    created_at: '2023-08-22T08:15:00Z',
  },
  {
    loan_id: 1007,
    customer_id: 107,
    customer_name: 'David Miller',
    customer_email: 'david.miller@example.com',
    loan_type: 'Business Loan',
    amount: '200,000',
    duration_months: 48,
    interest_rate: '7.5%',
    purpose: 'Equipment Purchase',
    status: 'closed',
    employment_status: 'Self-Employed',
    monthly_income: '9,500',
    id_doc_url: '/documents/david_id.pdf',
    bank_stmt_url: '/documents/david_bank.pdf',
    created_at: '2022-05-10T15:45:00Z',
  },
  {
    loan_id: 1008,
    customer_id: 108,
    customer_name: 'Lisa Anderson',
    customer_email: 'lisa.anderson@example.com',
    loan_type: 'Personal Loan',
    amount: '45,000',
    duration_months: 36,
    interest_rate: '8.8%',
    purpose: 'Medical Expenses',
    status: 'defaulted',
    employment_status: 'Employed',
    monthly_income: '4,200',
    id_doc_url: '/documents/lisa_id.pdf',
    bank_stmt_url: '/documents/lisa_bank.pdf',
    created_at: '2023-11-05T10:00:00Z',
  },
];

export const MOCK_CUSTOMER_ACCOUNTS: Record<number, CustomerAccount[]> = {
  101: [
    {
      account_id: 'ACC001',
      account_type: 'Current Account',
      account_number: '1234567890123',
      balance: '25,000',
      status: 'active',
    },
    {
      account_id: 'ACC002',
      account_type: 'Savings Account',
      account_number: '1234567890124',
      balance: '100,000',
      status: 'active',
    },
  ],
  102: [
    {
      account_id: 'ACC003',
      account_type: 'Business Account',
      account_number: '1234567890125',
      balance: '450,000',
      status: 'active',
    },
    {
      account_id: 'ACC004',
      account_type: 'Current Account',
      account_number: '1234567890126',
      balance: '85,000',
      status: 'active',
    },
  ],
  103: [
    {
      account_id: 'ACC005',
      account_type: 'Savings Account',
      account_number: '1234567890127',
      balance: '250,000',
      status: 'active',
    },
    {
      account_id: 'ACC006',
      account_type: 'Fixed Deposit Account',
      account_number: '1234567890128',
      balance: '500,000',
      status: 'active',
    },
  ],
  104: [
    {
      account_id: 'ACC007',
      account_type: 'Current Account',
      account_number: '1234567890129',
      balance: '120,000',
      status: 'active',
    },
  ],
  105: [
    {
      account_id: 'ACC008',
      account_type: 'Savings Account',
      account_number: '1234567890130',
      balance: '5,000',
      status: 'inactive',
    },
  ],
  106: [
    {
      account_id: 'ACC009',
      account_type: 'Savings Account',
      account_number: '1234567890131',
      balance: '15,000',
      status: 'active',
    },
  ],
  107: [
    {
      account_id: 'ACC010',
      account_type: 'Business Account',
      account_number: '1234567890132',
      balance: '750,000',
      status: 'active',
    },
  ],
  108: [
    {
      account_id: 'ACC011',
      account_type: 'Current Account',
      account_number: '1234567890133',
      balance: '8,000',
      status: 'active',
    },
  ],
};
